version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 5 
    assignees:
      - isaiah76
    labels:
      - "dependencies"
    groups:
      python-dependencies:
        patterns:
          - "discord.py"
          - "python-dotenv"
          - "langchain"
          - "langchain-google-genai"
          - "google-generativeai"
          - "Pillow"
          - "aiohttp"
